name: 'Jira ticket extractor'
description: 'Extract jira ticket from any string'
inputs:
  targetTransition:  # id of input
    description: 'Target transition'
    required: true
  sourceTransition:  # id of input
    description: 'Ticket needs to be in this status in order to be transitioned (not recomended)'
    required: false
  message:  # id of input
    description: 'Message to be posted as comment in the transitioned issue'
    required: false
  jiraBaseUrl:  # id of input
    description: 'Jira base url (something.atlassian.net)'
    required: true
  jiraEmail:  # id of input
    description: 'Jira user email'
    required: true
  jiraToken:  # id of input
    description: 'Jira user token'
    required: true
  githubToken:  # id of input
    description: 'git hub token'
    required: true
  fixVersion:  
    description: 'Assign version to tickets'
    required: false
  jiraProject:  
    description: 'Jira project (IW example)'
    required: false
  
runs:
  using: 'node16'
  main: 'index.js'
